---

- name: "Setting host facts using complex arguments"
  set_fact:
    pip_package_name: "python3-pip"
  when: ansible_distribution == "Debian"

- name: "Install python3-pip"
  package:
    name: "{{ pip_package_name }}"
    state: "latest"

- name: "Install docker-compose via pip"
  pip:
    name: "docker-compose"
    state: "latest"
