---
- name: "Ensure existence of operator group"
  group:
    name: "operator"
    state: "present"

- name: "Generate encrypted password"
  command: "mkpasswd --method=SHA-512 {{ 'item.pass' }}"
  register: encrypted_user_password

- name: "Adding User {{ item.username }}"
  user:
    name: "{{ item.username }}"
    create_home: yes
    comment: "automaticly added user"
    password: "{{ encrypted_user_password }}"
    shell: "{{ item.shell }}"
    update_password: "on_create"
    append: yes
    groups:
      - "ssh"
      - "sudo"
      - "operator"

- name: "Set authorized key taken from vault"
  authorized_key:
    user: "{{ item.username }}"
    state: "present"
    key: "{{ item.pubkey }}"
